# Generated by Django 4.2.6 on 2023-11-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('job_type', models.CharField(choices=[('part time', 'part time'), ('full time', 'full time')], max_length=50)),
            ],
        ),
    ]
