# Generated by Django 4.2.6 on 2023-11-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_experience_job_published_at_job_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='title',
        ),
    ]
